# .goreleaser.yml
# Build customization
project_name: kube-cleanup-operator

builds:
  - binary: kube-cleanup-operator
    main: ./cmd/main.go
    env:
    - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: arm64

release:
  github:
    owner: lwolf
    name: kube-cleanup-operator
  prerelease: true
  draft: true

dockers:
  - image: quay.io/lwolf/kube-cleanup-operator
    dockerfile: Dockerfile
    binary: kube-cleanup-operator
    goos: linux
    goarch: amd64
    tag_templates:
    - "{{ .Tag }}"
    - "latest"

git:
  short_hash: true
