# .goreleaser.yml
# Build customization
project_name: kube-cleanup-operator

builds:
  - binary: kube-cleanup-operator
    main: ./cmd/main.go
    env:
    - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - arm7
    ignore:
      - goos: darwin
        goarch: arm7
      - goos: darwin
        goarch: arm64

release:
  github:
    owner: lwolf
    name: kube-cleanup-operator
  prerelease: true

dockers:
  - dockerfile: Dockerfile.releaser
    binaries:
      - kube-cleanup-operator
    goos: linux
    goarch: amd64
    image_templates:
    - 'quay.io/lwolf/kube-cleanup-operator:{{ .Tag }}'
    - 'quay.io/lwolf/kube-cleanup-operator:latest'
